- name: Cassandra Setup
  hosts: "{{ host }}"
  become: true
  vars:
    ansible_ssh_user: "{{ admin_user }}"

  tasks:
  - name: Check if cassandra is installed
    stat:
      path: /opt/cassandra/bin/cassandra
    register: cassandra_exists

  - name: Install java
    when: not cassandra_exists.stat.exists
    apt:
      pkg:
        - default-jre

  - name: Create cassandra group
    when: not cassandra_exists.stat.exists
    group:
      name: cassandra
      system: yes

  - name: Create cassandra user
    when: not cassandra_exists.stat.exists
    user:
      name: cassandra
      group: cassandra
      shell: /sbin/nologin
      system: yes

  - name: Download cassandra
    when: not cassandra_exists.stat.exists
    get_url:
      url: "https://dlcdn.apache.org/cassandra/{{ cassandra_version }}/apache-cassandra-{{ cassandra_version }}-bin.tar.gz "
      dest: "/tmp/cassandra-{{ cassandra_version }}.tar.gz"
      mode: '0644'

  - name: Ensure /opt/cassandra directory exists
    file:
      path: /opt/cassandra
      owner: "cassandra"
      group: "cassandra"
      state: directory

  - name: Extract cassandra
    when: not cassandra_exists.stat.exists
    unarchive:
      src: "/tmp/cassandra-{{ cassandra_version }}.tar.gz"
      dest: /opt/cassandra/
      remote_src: yes
      owner: "cassandra"
      group: "cassandra"
      extra_opts:
        - --strip-components=1

  - name: Create Cassandra systemd service
    when: not cassandra_exists.stat.exists
    template:
      src: services/cassandra.service.j2
      dest: /etc/systemd/system/cassandra.service
    vars:
      cassandra_version: "{{ cassandra_version }}"
