- name: Elixir Setup
  hosts: "{{ host }}"

  vars:
    ansible_ssh_user: "{{ admin_user }}"

  tasks:
    # Install required packages
    - name: Update apt and install required system packages
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - autoconf
          - m4
          - libncurses5-dev
          - libgl1-mesa-dev
          - libglu1-mesa-dev
          - libpng-dev
          - libssh-dev
          - unixodbc-dev
          - xsltproc
          - fop
          - libxml2-utils
          - libncurses-dev
        state: latest
        update_cache: true

    ########## Install libssl1.1 ##########
    - name: Check if libssl1.1 is installed
      become: true
      ansible.builtin.shell:
        cmd: dpkg -l | grep libssl1.1
      register: libssl_check
      changed_when: false
      failed_when: libssl_check.rc not in [0, 1]

    - name: Download libssl1.1
      become: true
      register: download_libssl
      ansible.builtin.get_url:
        url: http://ftp.de.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
        dest: /root/
      when: libssl_check.rc != 0

    - name: Install libssl1.1
      become: true
      ansible.builtin.apt:
        deb: "{{ download_libssl.dest }}"
      when: libssl_check.rc != 0

    - name: Add Erlang plugin to asdf
      shell: asdf plugin add erlang

    - name: Add Erlang version to asdf
      shell: asdf install erlang {{ erlang_version }}

    - name: Set Erlang version as global
      shell: asdf global erlang {{ erlang_version }}

    - name: Add Elixir plugin to asdf
      shell: asdf plugin add elixir

    - name: Add Elixir version to asdf
      shell: asdf install elixir {{ elixir_version }}

    - name: Set Elixir version as global
      shell: asdf global elixir {{ elixir_version }}
