- name: Elixir Setup
  hosts: "{{ host }}"
  vars:
    erlang_version: 26.0
    elixir_version: 1.16.2-otp-26

  tasks:
    # Install required packages
    - name: Update apt and install required system packages
      become: true
      apt:
        pkg:
          - build-essential
          - autoconf
          - m4
          - libncurses5-dev
          - libwxgtk3.2-dev
          - libwxgtk-webview3.2-dev
          - libgl1-mesa-dev
          - libglu1-mesa-dev
          - libpng-dev
          - libssh-dev
          - unixodbc-dev
          - xsltproc
          - fop
          - libxml2-utils
          - libncurses-dev
          - openjdk-17-jdk
        state: latest
        update_cache: true
      vars:
        ansible_ssh_user: "{{ admin_user }}"

    - name: Clone asdf repository into ~/.asdf
      ansible.builtin.git:
        name: https://github.com/asdf-vm/asdf.git
        dest: ~/.asdf
        single_branch: yes
        version: v0.14.0

    - name: Insert lines to ~/.bashrc to source asdf
      ansible.builtin.blockinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        block: |
          . "$HOME/.asdf/asdf.sh"
          . "$HOME/.asdf/completions/asdf.bash"

    - name: Add Erlang plugin to asdf
      shell: /home/{{ ansible_user }}/.asdf/bin/asdf plugin add erlang

    - name: Add Erlang version to asdf
      shell: /home/{{ ansible_user }}/.asdf/bin/asdf install erlang {{ erlang_version }}

    - name: Set Erlang version as global
      shell: /home/{{ ansible_user }}/.asdf/bin/asdf global erlang {{ erlang_version }}

    - name: Add Elixir plugin to asdf
      shell: /home/{{ ansible_user }}/.asdf/bin/asdf plugin add elixir

    - name: Add Elixir version to asdf
      shell: /home/{{ ansible_user }}/.asdf/bin/asdf install elixir {{ elixir_version }}

    - name: Set Elixir version as global
      shell: /home/{{ ansible_user }}/.asdf/bin/asdf global elixir {{ elixir_version }}
