- name: Run setup playbook
  ansible.builtin.import_playbook: setup.yaml
  vars:
    host: explorer

- name: Run elixir playbook
  ansible.builtin.import_playbook: elixir.yaml
  vars:
    host: explorer

- name: Run nodejs playbook
  ansible.builtin.import_playbook: nodejs.yaml
  vars:
    host: explorer

- name: Run postgres playbook
  ansible.builtin.import_playbook: postgres.yaml
  vars:
    host: explorer

- hosts: explorer
  vars:
    service: "explorer"

  tasks:

    - name: Clone the aligned_layer repository
      ansible.builtin.git:
        repo: https://github.com/yetanotherco/aligned_layer
        dest: "{{ ansible_env.HOME }}/aligned_layer"
        update: yes
