- name: Run setup playbook
  ansible.builtin.import_playbook: setup.yaml
  vars:
    host: explorer

- name: Run elixir playbook
  ansible.builtin.import_playbook: elixir.yaml
  vars:
    host: explorer

- name: Run nodejs playbook
  ansible.builtin.import_playbook: nodejs.yaml
  vars:
    host: explorer

- name: Run postgres playbook
  ansible.builtin.import_playbook: postgres.yaml
  vars:
    host: explorer

- name: Run caddy playbook
  ansible.builtin.import_playbook: caddy.yaml
  vars:
    host: explorer

- hosts: explorer
  vars:
    service: "explorer"

  pre_tasks:
    - name: Install pnpm
      become: true
      ansible.builtin.shell:
        cmd: npm install -g pnpm
      vars:
        ansible_ssh_user: "{{ admin_user }}"

    - name: Clone the aligned_layer repository
      register: clone_repo
      ansible.builtin.git:
        repo: https://github.com/yetanotherco/aligned_layer
        dest: "{{ ansible_env.HOME }}/aligned_layer"
        update: yes

  tasks:
    - name: Add reverse proxy configuration to Caddyfile
      become: true
      blockinfile:
        path: /etc/caddy/Caddyfile
        block: |
          {{ caddy_explorer_url }} {
            tls {
              dns cloudflare {{ caddy_cloudflare_token }}
            }
            reverse_proxy localhost:{{ caddy_explorer_port }}
          }
        create: yes
        prepend_newline: true
      vars:
        ansible_ssh_user: "{{ admin_user }}"
        caddy_explorer_url: "{{ lookup('ini', 'caddy_explorer_url', file=ini_file) }}"
        caddy_explorer_port: 4000
        caddy_cloudflare_token: "{{ lookup('ini', 'caddy_cloudflare_token', file=ini_file) }}"

    - name: Build the explorer release
      args:
        chdir: "{{ clone_repo.git_dir_now }}"
      environment:
        MIX_ENV: prod
      ansible.builtin.shell:
        cmd: |
          set -ex
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only $MIX_ENV
          mix compile
          pnpm --prefix=assets/ install
          mix phx.digest
          mix assets.deploy
          mix release
